name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7","3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
        curl -X POST \
            -H "Authorization: token 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" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Vidushimodi/demo3/actions/workflows/6516173085/dispatches \
            -d '{"ref":"main"}'
